name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1

      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t diiviij/wisecow .
        docker push diiviij/wisecow

    - name: Deploy to Kubernetes
      uses: kubernetes/deploy-action@v1

      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        deployment: deployment.yaml
